title: My Jekyll Site
description: >-
  A simple Jekyll site on GitHub Pages.
# You can use any supported theme from GitHub Pages. E.g. "minima"
# theme: minima


email: zbule@bluestar03.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: zBuLe
github_username:  zBuLe

collections:
  destiny-saga:
    output: true
    permalink: /:collection/:name

defaults:
  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "zBuLe" 
 
